#!/usr/bin/env node
const fs=require('fs');
const m=fs.readFileSync('./parsed/questions_data.js','utf8').match(/const PREPARSED_QUESTIONS = (\[[\s\S]*\]);/);
const d=JSON.parse(m[1]);
let n=parseInt(d[d.length-1].id.substring(3));
const O=(l,t)=>({label:l,text:t});
const A=(s,ty,ti,opts,ans,exp)=>{
  n++; d.push({subject:s,type:ty,title:ti,options:opts||[],answer:ans,explanation:exp||'',topic:'',id:'GEN'+String(n).padStart(4,'0'),level:'B',correctCount:0,wrongCount:0,lastPractice:null,nextReview:null,reviewStage:0});
};
const H='HBase / ZooKeeper', L='Linux';

A(H,'单选题','如果想以列表的方式展示HBase中所有的用户表，应使用哪个命令?',[O('A','show'),O('B','get_table'),O('C','list'),O('D','describe')],'C','list命令列出所有用户表。');
A(H,'单选题','在HBase Java API中，获取指定表对象的方法是？',[O('A','Connection.getTable(TableName.valueOf("表名"))'),O('B','TableFactory.createTable("表名")'),O('C','Put.getTable("表名")'),O('D','HBaseConfiguration.getTable("表名")')],'A','Connection.getTable获取Table对象。');
A(H,'单选题','Zookeeper服务自身组成一个集群，若有2n+1个服务，允许失效的服务节点数是?',[O('A','n+1个'),O('B','0个'),O('C','n个'),O('D','2n个')],'C','ZK集群2n+1台允许n台失效(过半机制)。');
A(H,'单选题','HBase中BlockCache的主要作用是？',[O('A','缓存写操作日志'),O('B','管理Region的分裂与合并'),O('C','存储表的元数据信息'),O('D','缓存读取的数据块以提升查询效率')],'D','BlockCache是读缓存，缓存从HFile读取的数据块。');
A(L,'单选题','通过ll命令查看文件属性，某文件权限标识为lrw-rw-r--，该文件的类型以及文件所属用户拥有的操作权限为( )。',[O('A','链接文件、读写执行'),O('B','目录文件、读写执行'),O('C','链接文件、读写'),O('D','普通文件、读')],'C','l开头=链接文件；所有者rw-(读写)无x。');
A(H,'单选题','HBase中meta表的主要作用是？',[O('A','记录所有Region的位置信息'),O('B','管理HBase的命名空间'),O('C','协调集群节点的状态'),O('D','存储所有用户表的实际数据')],'A','meta表记录所有Region位置信息。');
A(H,'单选题','在Zookeeper的客户端命令中，用来查看指定节点下级的节点信息(不能递归查看)的命令是?',[O('A','help'),O('B','get'),O('C','ls'),O('D','set')],'C','ls查看子节点列表(不递归)。get获取数据。');
A(H,'单选题','在HBase Java API中，插入多行数据时，需要将多个Put对象放入哪个集合中？',[O('A','Queue'),O('B','Set'),O('C','List'),O('D','Map')],'C','table.put(List<Put>)接收List集合。');
A(H,'单选题','在HBase Java API中,用于判断表是否存在的方法是?',[O('A','table.exists(tableName)'),O('B','admin.exists(tableName)'),O('C','admin.tableExists(tableName)'),O('D','connection.tableExists(tableName)')],'C','HBaseAdmin.tableExists判断表存在。');
A(H,'单选题','HBase中Cell的数据类型是？',[O('A','字节码形式（无类型）'),O('B','字符串类型'),O('C','浮点类型'),O('D','整数类型')],'A','Cell数据以字节数组存储，无数据类型。');
A(H,'单选题','创建HBase maven项目时,以下哪个依赖是必须的?',[O('A','zookeeper'),O('B','hbase-client'),O('C','hadoop-common'),O('D','hbase-server')],'B','hbase-client是开发必须依赖。');
A(H,'单选题','HBase默认的安装运行模式是?',[O('A','单机模式'),O('B','云模式'),O('C','完全分布式模式'),O('D','伪分布式模式')],'A','默认单机模式(Standalone)。');
A(H,'单选题','在HBase Java API中,用于查看表详细描述的方法是?',[O('A','connection.getTableDescriptor()'),O('B','admin.listTables()'),O('C','table.getTableDescriptor()'),O('D','admin.getTableDescriptor()')],'D','admin.getTableDescriptor()获取表描述器。');
A(L,'单选题','普通用户登录Linux服务器后，需要完整切换为root管理员身份并加载全部系统环境变量，正确的切换命令是( )。',[O('A','su -'),O('B','sudo'),O('C','su ~'),O('D','sudo =')],'A','su - 完整切换root并加载环境变量。');
A(H,'单选题','HBase中RowKey在存储时的排序方式是？',[O('A','按行键长度排序'),O('B','随机排序'),O('C','按字典序（字节序）排序'),O('D','按插入顺序排序')],'C','RowKey按字典序(字节序)排序。');
A(H,'单选题','在HBase Java API中,用于创建表描述器的类是?',[O('A','TableDescriptorBuilder'),O('B','ColumnFamilyDescriptor'),O('C','TableDescriptor'),O('D','ColumnFamilyDescriptorBuilder')],'A','TableDescriptorBuilder构建表描述器。');
A(H,'单选题','在HBase Java API中,用于设置ZooKeeper地址的配置项是?',[O('A','zookeeper.address'),O('B','hbase.zookeeper.quorum'),O('C','hbase.zookeeper.address'),O('D','zookeeper.quorum')],'B','hbase.zookeeper.quorum配置ZK地址。');
A(H,'单选题','HBase中Cell的不同版本数据默认排序方式是？',[O('A','按时间戳升序排列'),O('B','按时间戳降序排列'),O('C','按数据大小排序'),O('D','按插入顺序排序')],'B','Cell版本默认按时间戳降序(最新在前)。');
A(L,'单选题','CentOS7系统编译Python相关拓展程序时，提示缺失Python.h头文件，安装哪个依赖包可解决该报错( )。',[O('A','gdb'),O('B','python3'),O('C','python3-devel'),O('D','gcc')],'C','python3-devel包含开发头文件(.h)。');
A(H,'单选题','在HBase集群中，若需修改数据表列族结构或彻底删除数据表，执行操作前必须完成的前置操作是( )。',[O('A','disable'),O('B','enable'),O('C','drop'),O('D','build')],'A','修改或删除表前必须先disable。');
A(H,'单选题','ZooKeeper集群采用主从架构模式，集群架构设计中，唯一允许存在的节点角色是( )。',[O('A','server'),O('B','follower'),O('C','node'),O('D','Leader')],'D','ZK中Leader是唯一主节点。');
A(H,'单选题','在HBase Java API中，用于插入单行数据的类是？',[O('A','Get'),O('B','Delete'),O('C','Put'),O('D','Scan')],'C','Put类插入/更新单行数据。');
A(H,'单选题','Zookeeper每一个ZNode默认能够存储的数据大小是?',[O('A','1GB'),O('B','1KB'),O('C','1MB'),O('D','10MB')],'C','每个ZNode默认最大1MB。');
A(H,'单选题','在HBase完全分布式配置中，要告诉HBase使用外部的Zookeeper，需要在hbase-env.sh中将HBASE_MANAGES_ZK设置为?',[O('A','true'),O('B','yes'),O('C','false'),O('D','no')],'C','false使用外部ZK。');
A(H,'单选题','以下哪项是HMaster的核心功能？',[O('A','处理客户端的具体读写请求'),O('B','提供分布式协调服务'),O('C','管理Region的分配与负载均衡'),O('D','存储HBase的实际数据')],'C','HMaster核心：Region分配/负载均衡。');
A(H,'单选题','在Zookeeper集群配置zoo.cfg中，server.N=YYY:A:B中的A代表什么含义?',[O('A','选举新leader时服务器间相互通信的端口'),O('B','该服务器与集群中的leader交换信息的通信端口'),O('C','客户端连接端口'),O('D','服务器的IP地址')],'A','A是Leader选举通信端口(2888)。');
A(H,'单选题','HBase中用于向表中插入数据的命令是?',[O('A','append'),O('B','insert'),O('C','put'),O('D','update')],'C','put命令插入/更新数据。');
A(H,'单选题','关于删除命名空间(namespace)，以下说法正确的是?',[O('A','可以删除任何状态的命名空间'),O('B','必须先删除所有表但不能删除命名空间'),O('C','只能删除空的命名空间'),O('D','只能删除非空的命名空间')],'C','只能删除空的命名空间。');
A(H,'单选题','以下哪种接口支持REST风格的Http API访问HBase，并且解除了语言限制?',[O('A','Pig'),O('B','REST Gateway'),O('C','Hive'),O('D','Thrift Gateway')],'B','REST Gateway提供HTTP API。');
A(L,'单选题','当Linux服务器出现僵尸进程、卡死进程，需要强制终止进程运行，对应的专属操作命令是( )。',[O('A','end'),O('B','tail'),O('C','ps'),O('D','kill')],'D','kill命令终止进程(kill -9强制)。');
A(L,'单选题','配置Linux服务器SSH免密登录功能时，用于存储客户端公钥、授权免密访问的标准文件名称是( )。',[O('A','authorized-keys'),O('B','authorized_key'),O('C','authorized-key'),O('D','authorized_keys')],'D','SSH公钥存在~/.ssh/authorized_keys。');
A(L,'单选题','Vim编辑器拥有多种常规操作模式，下列选项中，不属于其标准内置工作模式的是( )。',[O('A','插入模式'),O('B','末行模式'),O('C','命令模式'),O('D','修订模式')],'D','Vim三大模式：命令/插入/末行。修订模式不存在。');
A(L,'单选题','Linux系统中tar zxvf解压指令适配特定压缩格式，该指令可解压的文件类型是( )。',[O('A','tar.bz2'),O('B','zip'),O('C','tar.gz'),O('D','tar.xz')],'C','tar zxvf中z用gzip对应.tar.gz。');
A(H,'单选题','在HBase Java API中，字符串转换为字节数组的方法是？',[O('A','String.toBytes()'),O('B','String.getBytes()'),O('C','Bytes.toBytes(String)'),O('D','Byte.parseByte(String)')],'C','HBase用Bytes.toBytes转字节数组。');
A(H,'单选题','在HBase Java API中，向Put对象添加列数据时，需要指定的参数不包括？',[O('A','列值'),O('B','列族名称'),O('C','列名称'),O('D','时间戳')],'D','addColumn(列族,列,值)三个必须。时间戳可选。');
A(H,'单选题','HBase中可通过以下哪种方式回收Cell的旧版本数据？',[O('A','仅保存最近一段时间内的版本'),O('B','无法自动回收旧版本数据'),O('C','保存最后n个版本或最近一段时间内的版本'),O('D','仅保存最后n个版本')],'C','可通过VERSIONS或TTL回收旧版本。');
A(L,'单选题','若需永久关闭防火墙开机自启功能，禁止虚拟机开机自动启动防火墙服务，对应的正确命令是( )。',[O('A','systemctl enable firewalld'),O('B','systemctl disable firewalld'),O('C','systemctl stop firewalld'),O('D','systemctl restart firewalld')],'B','systemctl disable禁止开机自启。');
A(H,'单选题','关于HBase列限定符（Column Qualifier）的描述，正确的是？',[O('A','同一表中所有行的列限定符必须一致'),O('B','列限定符不可动态添加'),O('C','列限定符必须属于某个列族'),O('D','表创建时必须指定列限定符')],'C','列限定符必须属于某个列族，可动态添加。');
A(H,'单选题','在HBase Java API中，扫描全表数据的类是？',[O('A','Scan'),O('B','Get'),O('C','Delete'),O('D','Put')],'A','Scan类扫描全表或多行。');
A(H,'单选题','在HBase Java API中，根据rowkey查询单行数据的类是？',[O('A','Delete'),O('B','Get'),O('C','Put'),O('D','Scan')],'B','Get类根据rowkey查询单行。');
A(H,'单选题','在HBase Java API中,用于查看所有表名称的方法是?',[O('A','admin.listTables()'),O('B','admin.listTableNames()'),O('C','connection.listTableNames()'),O('D','table.listTables()')],'B','admin.listTableNames()返回表名数组。');
A(H,'单选题','访问HBase最常规和高效的访问方式是?',[O('A','REST Gateway'),O('B','HBase Shell'),O('C','Native Java API'),O('D','Thrift Gateway')],'C','Native Java API最直接高效。');
A(H,'单选题','在HBase Java API中，创建与HBase集群连接的类是？',[O('A','ConnectionFactory'),O('B','Table'),O('C','HBaseConfiguration'),O('D','Put')],'A','ConnectionFactory.createConnection创建连接。');
A(H,'单选题','在HBase Java API中，用于创建HBase配置对象的工具类是？',[O('A','HBaseConfiguration'),O('B','TableFactory'),O('C','ConfigurationFactory'),O('D','ConnectionFactory')],'A','HBaseConfiguration.create()创建配置。');
A(H,'单选题','大数据环境中，一键批量启动所有HBase集群服务节点的官方标准脚本是( )。',[O('A','start-hbase.sh'),O('B','start hbase'),O('C','start-hbase'),O('D','hbase start')],'A','start-hbase.sh官方启动脚本。');
A(L,'单选题','运维人员日常远程操控云Linux服务器，实现远程连接登录的标准专用指令是( )。',[O('A','Ssh'),O('B','login'),O('C','SSH'),O('D','ssm')],'C','SSH(Secure Shell)远程登录协议。');
A(H,'单选题','关于HBase列族的描述，正确的是？',[O('A','列族在表创建时必须指定'),O('B','表创建后可动态添加列族'),O('C','不同列族的数据存储在同一个Store中'),O('D','一个表中建议创建超过5个列族')],'A','列族在创建表时必须指定。建议不超过3个。');
A(H,'单选题','在HBase Shell交互命令行中，执行status指令的主要作用是( )。',[O('A','返回Linux集群的状态信息'),O('B','返回HBase集群的状态信息'),O('C','返回ZooKeeper集群的状态信息'),O('D','返回Hadoop集群的状态信息')],'B','status返回HBase集群状态。');
A(H,'单选题','在HBase Java API中，获取Scan扫描结果的方法是？',[O('A','Table.getScanner(Scan)'),O('B','Connection.getTable(TableName)'),O('C','Table.get(Get)'),O('D','Put.addColumn()')],'A','Table.getScanner返回ResultScanner。');
A(H,'单选题','需要进入ZooKeeper交互式客户端命令行界面，可执行的正确脚本命令是( )。',[O('A','zkServer.sh'),O('B','zkCli.sh'),O('C','zkServer.sh start'),O('D','zkCli.sh start')],'B','zkCli.sh启动ZK客户端。');
A(H,'单选题','在HBase Java API中,创建表的正确顺序是?',[O('A','创建表描述器→创建列族描述器→关联列族→创建表'),O('B','创建列族描述器→创建表描述器→关联列族→创建表'),O('C','创建表描述器→关联列族→创建列族描述器→创建表'),O('D','创建列族描述器→关联列族→创建表描述器→创建表')],'A','顺序：表描述器→列族描述器→关联列族→admin.createTable。');
A(H,'单选题','Zookeeper节点类型中，客户端与ZooKeeper断开连接后，该节点依旧存在，只是ZooKeeper给该节点名称进行顺序编号的节点是?',[O('A','临时节点'),O('B','持久节点'),O('C','持久顺序节点'),O('D','临时顺序节点')],'C','持久顺序节点断开后仍存并自动编号。');
A(H,'单选题','关于HBase Region的描述，正确的是？',[O('A','Region的划分依据是行键的随机范围'),O('B','一个Region Server只能管理一个Region'),O('C','一个Region只能包含一个表的部分数据'),O('D','Region在HDFS上以单个文件形式存储')],'C','Region是表水平分区存部分数据。');
A(L,'单选题','Linux系统拥有规范的层级目录结构，系统内置的基础可执行命令文件，默认统一存放于哪个目录中( )。',[O('A','/dev'),O('B','/bin'),O('C','/root'),O('D','/home')],'B','/bin存放系统基本命令。');
A(H,'单选题','市面上主流数据库类型分为关系型与非关系型，下列数据库中，不属于NoSQL非关系型数据库的是( )。',[O('A','HBase'),O('B','Oracle'),O('C','MongoDB'),O('D','Redis')],'B','Oracle是关系型数据库。');
A(H,'单选题','在HBase集群中，Zookeeper不负责以下哪项功能？',[O('A','记录meta表的存储位置'),O('B','协助HMaster处理客户端读写请求'),O('C','监控集群节点运行状态'),O('D','存储HBase的所有数据文件')],'D','ZK不存储数据文件(数据在HDFS)。');
A(H,'单选题','在HBase Java API中,静态代码块的作用是?',[O('A','插入数据'),O('B','创建表'),O('C','初始化配置和连接'),O('D','查询数据')],'C','static代码块初始化配置和连接。');
A(H,'单选题','配置HBase环境变量时，一般在以下哪个文件中设置root用户的环境变量?',[O('A','zoo.cfg'),O('B','/etc/hostname'),O('C','/etc/profile'),O('D','/etc/hosts')],'C','/etc/profile系统级环境变量。');
A(H,'单选题','在HBase Java API中，获取Get查询结果的方法是？',[O('A','Connection.getTable(TableName)'),O('B','Table.scan(Scan)'),O('C','Table.get(Get)'),O('D','Put.addColumn()')],'C','Table.get(Get)返回Result。');
A(H,'单选题','HBase中每个Store对应的是表中的哪个逻辑概念？',[O('A','时间戳'),O('B','行'),O('C','单元格'),O('D','列族')],'D','每个Store对应一个列族。');
A(H,'单选题','HBase中清空表数据(truncate)的内部实际执行顺序是?',[O('A','disable -> drop -> recreate'),O('B','disable -> clear -> enable'),O('C','deleteall -> drop -> create'),O('D','drop -> disable -> recreate')],'A','truncate=disable→drop→recreate。');
A(H,'单选题','HBase shell中用于查看集群状态、版本等基础操作属于哪个命令组?',[O('A','namespace'),O('B','dml'),O('C','ddl'),O('D','general')],'D','general命令组(status/version/whoami)。');
A(H,'单选题','在HBase Shell交互终端中，用于创建新的数据表的专属操作指令是( )。',[O('A','new'),O('B','make'),O('C','Create'),O('D','create')],'D','create命令创建表(小写)。');
A(H,'单选题','在HBase Shell环境中，可实现单元格数据新增与数据修改更新的统一操作指令是( )。',[O('A','sent'),O('B','set'),O('C','update'),O('D','put')],'D','put同时实现新增和修改(有则覆盖)。');
A(H,'单选题','在HBase Java API中,用于设置列族最大版本数的方法是?',[O('A','setMaxVersions()'),O('B','setVersion()'),O('C','setMinVersions()'),O('D','setVersions()')],'A','setMaxVersions()设置最大版本数。');
A(H,'单选题','在HBase Java API中,用于创建连接的类是?',[O('A','HBaseAdmin'),O('B','HBaseConfiguration'),O('C','ConnectionFactory'),O('D','Table')],'C','ConnectionFactory创建连接。');
A(H,'单选题','HBase从1.0版本之后，默认的Web UI访问端口号从60010改为了多少?',[O('A','16030'),O('B','0.98'),O('C','16020'),O('D','16010')],'D','HBase 1.0+ Master UI默认16010。');
A(H,'单选题','在HBase Java API中,用于创建列族描述器的类是?',[O('A','TableDescriptorBuilder'),O('B','ColumnFamilyDescriptorBuilder'),O('C','TableDescriptor'),O('D','ColumnFamilyDescriptor')],'B','ColumnFamilyDescriptorBuilder构建列族描述器。');
A(H,'单选题','采用解压方式部署HBase服务后，项目所有核心配置文件默认的存放目录为( )。',[O('A','hbase/etc/'),O('B','hbase/conf/'),O('C','/etc/hbase/'),O('D','/conf/hbase/')],'B','配置文件在hbase/conf/目录。');
A(H,'单选题','在HBase Java API中,创建连接时可能抛出的异常是?',[O('A','ClassNotFoundException'),O('B','IOException'),O('C','NullPointerException'),O('D','SQLException')],'B','createConnection可能抛IOException。');
A(H,'单选题','在HBase中，能够删除一整行数据的命令是?',[O('A','remove'),O('B','delete'),O('C','drop'),O('D','deleteall')],'D','deleteall删除整行。delete删指定列。');
A(H,'单选题','HBase分布式模式细分为伪分布式与完全分布式，其中完全分布式模式只能运行在( )上?',[O('A','NTFS'),O('B','本地文件系统'),O('C','Ext4'),O('D','HDFS')],'D','完全分布式必须运行在HDFS上。');
A(H,'单选题','在HBase Java API中，修改数据的操作与以下哪种操作的实现方式相同？',[O('A','插入数据'),O('B','删除数据'),O('C','查询数据'),O('D','扫描数据')],'A','HBase修改=插入新版本(Put)。');
A(H,'单选题','在Windows环境搭建HBase开发环境时,以下哪个文件需要放到C:\\Windows\\System32目录?',[O('A','core-site.xml'),O('B','winutils.exe'),O('C','hbase-site.xml'),O('D','hadoop.dll')],'D','hadoop.dll放System32。');
A(H,'单选题','HBase中HLog（WAL）的主要作用是？',[O('A','存储表的元数据信息'),O('B','管理Region的分裂与合并'),O('C','记录写操作日志以防止数据丢失'),O('D','缓存读取的数据以提升查询效率')],'C','HLog(WAL)先写日志防数据丢失。');
A(H,'单选题','在HBase中删除表之前，必须先执行的操作状态命令是?',[O('A','enable'),O('B','disable'),O('C','exists'),O('D','truncate')],'B','删表前必须先disable。');
A(H,'单选题','以下关于HBase Java API的描述,错误的是?',[O('A','HBase Java API效率高因为HBase本身由Java编写'),O('B','HBase 1.x和2.x版本的Java API完全相同'),O('C','可以通过Java API操作HBase表数据'),O('D','Java API比shell命令更灵活')],'B','1.x和2.x API有差异(2.x用Builder模式)。');
A(H,'单选题','HBase中默认的用户表命名空间是？',[O('A','system'),O('B','default'),O('C','hbase'),O('D','user')],'B','默认命名空间default。');
A(H,'单选题','HBase客户端发起数据读写请求时，需先访问哪个组件获取数据表元数据与节点位置信息( )。',[O('A','master'),O('B','Region'),O('C','Zookeeper'),O('D','RegionServer')],'C','客户端先访问ZK获取meta表位置。');
A(H,'单选题','在HBase命令行工具中，退出HBase shell可以使用的命令是?',[O('A','quit'),O('B','stop'),O('C','shutdown'),O('D','close')],'A','quit或exit退出HBase Shell。');

const newJs='const PREPARSED_QUESTIONS = '+JSON.stringify(d,null,2)+';';
fs.writeFileSync('./parsed/questions_data.js','// 六科完整题库 — '+d.length+'题\n'+newJs,'utf8');
fs.writeFileSync('./parsed/questions_data.json', JSON.stringify(d,null,2), 'utf8');
console.log('Added 80 MC, total:', d.length);
const subj={}; d.forEach(q=>{subj[q.subject]=(subj[q.subject]||0)+1;});
Object.entries(subj).sort((a,b)=>b[1]-a[1]).forEach(([s,n])=>console.log(s+': '+n));
