// 六科完整知识清单 — 从1082道题库 + 老师重点精炼（v3）
const CHECKLIST = [
  // ==================== Java Web (40条) ====================
  {id:'jw01',subj:'Java Web',lvl:'A',item:'JSP页面7类内容：静态HTML、指令<%@ %>、表达式<%= %>、Scriptlet<% %>、声明<%! %>、动作<jsp:>、注释<%-- --%>'},
  {id:'jw02',subj:'Java Web',lvl:'A',item:'JSP执行四步：客户端Request→JSP转译成Servlet源码→编译成.class→执行Response。再次请求直接用.class'},
  {id:'jw03',subj:'Java Web',lvl:'A',item:'两个时期：转译时期(JSP→java→class,仅首次)+请求时期(执行class,每次请求)'},
  {id:'jw04',subj:'Java Web',lvl:'A',item:'JSP三大脚本元素：表达式<%= %>无分号、Scriptlet<% %>有分号、声明<%! %>定义成员(多线程共享注意安全)'},
  {id:'jw05',subj:'Java Web',lvl:'A',item:'JSP三大指令：page(导包/编码/错误页)、include(编译时静态包含)、taglib(引入JSTL)'},
  {id:'jw06',subj:'Java Web',lvl:'A',item:'9大隐式对象：request/response/session/application/config/out/page/pageContext/exception'},
  {id:'jw07',subj:'Java Web',lvl:'A',item:'四大作用域从小到大：page<request<session<application。购物车用session，访问量用application'},
  {id:'jw08',subj:'Java Web',lvl:'A',item:'静态include(<%@ include %>)编译时合并→1个class→不能传参 vs 动态include(<jsp:include>)运行时合并→多个class→可传参'},
  {id:'jw09',subj:'Java Web',lvl:'A',item:'Servlet生命周期：init()首次1次→service/doGet/doPost每次请求→destroy()关闭时1次。单例多线程'},
  {id:'jw10',subj:'Java Web',lvl:'A',item:'请求转发forward：URL不变/1次请求/可共享request/不能跨域/快。重定向sendRedirect：URL变/2次请求/不能共享/可跨域'},
  {id:'jw11',subj:'Java Web',lvl:'A',item:'Filter过滤器：init→doFilter→destroy。必须chain.doFilter()放行！典型应用：IP过滤/编码/权限'},
  {id:'jw12',subj:'Java Web',lvl:'A',item:'MVC三层：M模型(JavaBean/DAO数据+业务)、V视图(JSP展示)、C控制器(Servlet调度)。各司其职'},
  {id:'jw13',subj:'Java Web',lvl:'A',item:'Session vs Cookie：Session服务器(安全)/Cookie浏览器(≤4KB)。Session存登录信息，Cookie存偏好'},
  {id:'jw14',subj:'Java Web',lvl:'A',item:'ServletConfig(单个Servlet配置)vs ServletContext(全局共享)。获取：getServletConfig()/getServletContext()'},
  {id:'jw15',subj:'Java Web',lvl:'A',item:'JSP动作标签：<jsp:useBean>创建对象、<jsp:setProperty>设值、<jsp:getProperty>取值、<jsp:forward>转发'},
  {id:'jw16',subj:'Java Web',lvl:'A',item:'JavaBean规范：public类+private属性+public getter/setter+无参构造。boolean用isXxx()'},
  {id:'jw17',subj:'Java Web',lvl:'A',item:'JDBC四步：Class.forName加载→DriverManager连接→Statement执行SQL→关闭ResultSet/Statement/Connection'},
  {id:'jw18',subj:'Java Web',lvl:'A',item:'MVC登录模板：login.jsp→LoginServlet(取参调Dao验证)→成功redirect/welcome.jsp，失败forward/login.jsp+错误信息'},
  {id:'jw19',subj:'Java Web',lvl:'A',item:'web.xml配置Servlet：<servlet>(name+class)和<servlet-mapping>(name+url-pattern)两对标签'},
  {id:'jw20',subj:'Java Web',lvl:'B',item:'JSTL标签：<c:if>单分支(无else)、<c:choose>/<c:when>/<c:otherwise>多分支、<c:forEach>循环、<c:set>设变量'},
  {id:'jw21',subj:'Java Web',lvl:'B',item:'EL表达式${}：获取数据/执行运算/获取隐式对象。${empty xxx}判断null或空'},
  {id:'jw22',subj:'Java Web',lvl:'B',item:'Tomcat：默认端口8080(conf/server.xml改)、WEB-INF不可直接访问、work存编译类、webapps部署目录'},
  {id:'jw23',subj:'Java Web',lvl:'B',item:'HTTP状态码：200成功、302重定向、404未找到、500服务器错误。GET参数URL可见(不安全)，POST在请求体(安全)'},
  {id:'jw24',subj:'Java Web',lvl:'B',item:'编码三统一：JSP pageEncoding="UTF-8"、request.setCharacterEncoding("UTF-8")、response.setContentType'},
  {id:'jw25',subj:'Java Web',lvl:'B',item:'Servlet继承：Servlet接口→GenericServlet抽象类→HttpServlet(重写doGet/doPost)'},
  {id:'jw26',subj:'Java Web',lvl:'B',item:'GenericServlet是抽象类(不是接口!)同时实现Servlet和ServletConfig，service是抽象方法'},
  {id:'jw27',subj:'Java Web',lvl:'B',item:'Cookie操作：new Cookie→setMaxAge→response.addCookie。Session：request.getSession().setAttribute()'},
  {id:'jw28',subj:'Java Web',lvl:'B',item:'PreparedStatement vs Statement：预编译防SQL注入，用?占位符，setXxx()设参数'},
  {id:'jw29',subj:'Java Web',lvl:'B',item:'域对象通用API：setAttribute存、getAttribute取、removeAttribute删。四大作用域都适用'},
  {id:'jw30',subj:'Java Web',lvl:'B',item:'page指令属性：import导包、pageEncoding编码、contentType响应类型、errorPage错误页、isErrorPage是否错误页'},
  {id:'jw31',subj:'Java Web',lvl:'C',item:'web.xml还可配：welcome-file欢迎页、error-page错误页、context-param全局参数、filter过滤器、session-timeout'},
  {id:'jw32',subj:'Java Web',lvl:'C',item:'@WebServlet("/url")注解可替代web.xml配置(Servlet 3.0+)。loadOnStartup设启动加载顺序'},
  {id:'jw33',subj:'Java Web',lvl:'C',item:'Tomcat目录：/bin脚本、/conf配置、/work编译类、/webapps项目、/lib全局jar、/logs日志、/temp临时'},
  {id:'jw34',subj:'Java Web',lvl:'C',item:'JSP注释<%-- -->客户端不可见；HTML注释<!-- -->客户端可见。考试常考区别'},
  {id:'jw35',subj:'Java Web',lvl:'C',item:'Servlet线程安全：Servlet是单例的，不要用成员变量存请求相关数据，用局部变量'},
  {id:'jw36',subj:'Java Web',lvl:'B',item:'RequestDispatcher：request.getRequestDispatcher("url").forward(req,resp)转发；.include()包含'},
  {id:'jw37',subj:'Java Web',lvl:'B',item:'getParameter()获取单值；getParameterValues()获取多值(如checkbox)；getParameterNames()获取所有参数名'},
  {id:'jw38',subj:'Java Web',lvl:'B',item:'FilterConfig提供：getInitParameter()、getFilterName()、getServletContext()'},
  {id:'jw39',subj:'Java Web',lvl:'C',item:'JSP的out对象是JspWriter类型、page对象是Object类型(this)、config对象是ServletConfig类型'},
  {id:'jw40',subj:'Java Web',lvl:'C',item:'exception对象仅isErrorPage="true"的页面可用，是Throwable类型'},

  // ==================== Linux (35条) ====================
  {id:'lx01',subj:'Linux',lvl:'A',item:'文件命令：ls -la(全部详情)、cd ~(回家)/(根)/..(上级)、pwd(当前路径)、mkdir -p(递归)、rm -rf(强删)、cp/mv/touch'},
  {id:'lx02',subj:'Linux',lvl:'A',item:'查看文件：cat(全部)、more(单向分页)、less(双向可搜索)、head -n(前N行默认10)、tail -n(后N行)、tail -f(实时)'},
  {id:'lx03',subj:'Linux',lvl:'A',item:'chmod权限：数字法(r=4 w=2 x=1) 7=rwx 6=rw- 5=r-x 4=r--。chmod 755最常用'},
  {id:'lx04',subj:'Linux',lvl:'A',item:'chmod字符法：u/g/o/a +-= rwx。chmod u+x(加执行)、chmod g-w(去写)、chmod a+rwx(=777)'},
  {id:'lx05',subj:'Linux',lvl:'A',item:'vi/vim三模式：命令模式(默认移删复粘)→输入模式(i/a/o进入Esc退出)→末行模式(:wq保存退出 :q!强退)'},
  {id:'lx06',subj:'Linux',lvl:'A',item:'vim常用：dd删行、yy复制、p粘贴、u撤销、.重复、G末行、gg首行、/搜索、:set nu行号、:set nonu取消'},
  {id:'lx07',subj:'Linux',lvl:'A',item:'用户管理：useradd创建、userdel -r删用户+家目录(不加-r仅删账号)、passwd设密码、su切换用户'},
  {id:'lx08',subj:'Linux',lvl:'A',item:'Shell脚本：首行#!/bin/bash、变量赋值等号无空格(name=value)、引用$name、$#参数个数、$?退出状态'},
  {id:'lx09',subj:'Linux',lvl:'A',item:'Shell条件与循环：if [条件];then...fi、for i in...;do...done、while...do...done、case...in...esac'},
  {id:'lx10',subj:'Linux',lvl:'B',item:'tar压缩：tar -zcvf 包名.tar.gz 源(打包压缩)、tar -zxvf 包名.tar.gz(解压)、-C指定目录。c创建x解压z用gzip'},
  {id:'lx11',subj:'Linux',lvl:'B',item:'管道|：前命令输出作后命令输入。重定向：>覆盖 >>追加 2>错误 2>&1错误合并到标准输出 <输入'},
  {id:'lx12',subj:'Linux',lvl:'B',item:'grep查找：grep "关键词" 文件、-i忽略大小写、-n行号、-v反向、-r递归。sed流编辑器直接修改文件'},
  {id:'lx13',subj:'Linux',lvl:'B',item:'进程：ps -aux(查看全部)、top(实时)、kill PID(终止)、kill -9(强杀)、killall(终止同名)、&后台、Ctrl+C终止'},
  {id:'lx14',subj:'Linux',lvl:'B',item:'软链接ln -s：类似快捷方式删源失效可跨文件系统。硬链接ln：共享inode删源仍可用不能跨文件系统'},
  {id:'lx15',subj:'Linux',lvl:'B',item:'目录结构：/bin命令 /etc配置 /home用户 /root超管 /tmp临时 /usr程序 /var日志 /boot内核 /dev设备'},
  {id:'lx16',subj:'Linux',lvl:'B',item:'关机重启：shutdown -h now/poweroff/halt(关机)、reboot(重启)、shutdown -h +30(定时)、shutdown -c(取消)'},
  {id:'lx17',subj:'Linux',lvl:'B',item:'用户进阶：useradd -d指定家目录、usermod修改用户(不能删账户!)、groupadd创建组、chown改所有者'},
  {id:'lx18',subj:'Linux',lvl:'B',item:'Shell引号：单引号不解释变量、双引号解释变量、反引号或$()命令替换。变量默认都是字符串类型'},
  {id:'lx19',subj:'Linux',lvl:'B',item:'文件类型：-普通文件 d目录 l链接文件。权限三组rwx=所有者+所属组+其他人。权限用ls -l查看'},
  {id:'lx20',subj:'Linux',lvl:'B',item:'正则元字符：.任意字符 *零或多次 ^行首 $行尾 []字符集 [^]排除。配合grep/sed使用'},
  {id:'lx21',subj:'Linux',lvl:'C',item:'Linux特点：与UNIX兼容、开源、高性能安全、可定制、互操作、真正多任务、服务器+嵌入式广泛。CentOS7主流'},
  {id:'lx22',subj:'Linux',lvl:'C',item:'gzip压缩单个文件(.gz)、gunzip解压。zip -r打包(zip格式)、unzip解压。tar是打包+gzip的整合方案'},
  {id:'lx23',subj:'Linux',lvl:'C',item:'磁盘相关：df -h(查看磁盘使用)、du -sh(目录大小)、mount(挂载)、fdisk -l(分区)。inode存文件元信息'},
  {id:'lx24',subj:'Linux',lvl:'B',item:'文件描述符：0=stdin标准输入、1=stdout标准输出、2=stderr标准错误。2>&1把错误合并到输出'},
  {id:'lx25',subj:'Linux',lvl:'B',item:'vim模式切换：命令→输入(i/a/o)、输入→命令(Esc)、命令→末行(:)、末行→命令(执行完/Esc)'},
  {id:'lx26',subj:'Linux',lvl:'C',item:'sed常用：s/旧/新/g替换、d删除行、p打印、-i直接修改文件。与grep区别：sed可改文件grep只能查'},
  {id:'lx27',subj:'Linux',lvl:'B',item:'bash配置文件：~/.bashrc(用户级)、/etc/profile(系统级)。source使其生效。export导出为环境变量'},
  {id:'lx28',subj:'Linux',lvl:'C',item:'vi可视模式：v字符可视、V行可视、Ctrl+v块可视。用于批量选中文本后复制删除'},
  {id:'lx29',subj:'Linux',lvl:'C',item:'cal日历：cal(当月)、cal 6 2026(指定年月)、cal -y(全年)、cal -3(三月)。date查看设置系统日期'},
  {id:'lx30',subj:'Linux',lvl:'C',item:'命令别名：alias ll="ls -l"创建别名、unalias取消。which查找命令位置。history查看历史命令'},
  {id:'lx31',subj:'Linux',lvl:'B',item:'文件权限数字速算：rwx=4+2+1=7、rw-=4+2=6、r-x=4+1=5、r--=4。三组拼接如755=rwxr-xr-x'},
  {id:'lx32',subj:'Linux',lvl:'C',item:'777权限=所有人全部权限(rwxrwxrwx)，风险极高生产环境禁用。644是文件默认(rw-r--r--)。755是目录默认'},
  {id:'lx33',subj:'Linux',lvl:'C',item:'链接文件权限位l开头(如lrwxrwxrwx)。硬链接与原文件权限相同。软链接权限=777但实际由源文件控制'},
  {id:'lx34',subj:'Linux',lvl:'C',item:'declare -i声明整数变量、-a声明数组、-r只读、-x导出为环境变量。Shell默认都是字符串类型'},
  {id:'lx35',subj:'Linux',lvl:'B',item:'scp远程拷贝、ssh远程登录、wget下载文件、curl发送HTTP请求。netstat查看网络端口'},

  // ==================== Hadoop (35条) ====================
  {id:'hd01',subj:'Hadoop',lvl:'A',item:'HDFS架构：NameNode(元数据管理"目录")、DataNode(存实际数据块)、SecondaryNameNode(合并fsimage+edits，不是热备)'},
  {id:'hd02',subj:'Hadoop',lvl:'A',item:'YARN架构：ResourceManager(全局调度)、NodeManager(节点管理)、ApplicationMaster(应用资源申请)、Container(CPU+内存抽象)'},
  {id:'hd03',subj:'Hadoop',lvl:'A',item:'Block默认128MB(Hadoop 2.x)、副本数默认3(dfs.replication)。500MB=4Block(128+128+128+116)'},
  {id:'hd04',subj:'Hadoop',lvl:'A',item:'副本放置策略：机架感知→第一个客户端节点、第二个不同机架、第三个同机架不同节点'},
  {id:'hd05',subj:'Hadoop',lvl:'A',item:'HDFS命令：-ls/-ls -R列出、-mkdir -p递归创建、-put上传、-get下载、-cat查看、-rm -r递归删、-getmerge合并下载'},
  {id:'hd06',subj:'Hadoop',lvl:'A',item:'MapReduce流程：Input→Split→Map→Shuffle→Reduce→Output。Map数=Split数。默认Reduce=1'},
  {id:'hd07',subj:'Hadoop',lvl:'A',item:'Map输入key=LongWritable(偏移量)、value=Text(行内容)。Shuffle是MR核心环节(分区排序归并)'},
  {id:'hd08',subj:'Hadoop',lvl:'A',item:'HDFS不适合小文件：NameNode元数据压力大、降低吞吐、Map任务浪费。解决：SequenceFile/HBase合并'},
  {id:'hd09',subj:'Hadoop',lvl:'A',item:'HDFS写流程：Client→NameNode(获取DN列表)→DN间Pipeline管道复制→全部完成返回确认'},
  {id:'hd10',subj:'Hadoop',lvl:'A',item:'HDFS读流程：Client→NameNode(获取Block位置)→按就近原则从DN读取→合并返回'},
  {id:'hd11',subj:'Hadoop',lvl:'A',item:'YARN工作流程：Client提交RM→RM启动AM→AM向Scheduler申请资源→与NM通信启动Container执行Task'},
  {id:'hd12',subj:'Hadoop',lvl:'B',item:'core-site.xml→fs.defaultFS(HDFS地址)。hdfs-site.xml→dfs.replication(副本数)'},
  {id:'hd13',subj:'Hadoop',lvl:'B',item:'yarn-site.xml→yarn.resourcemanager.hostname。mapred-site.xml→mapreduce.framework.name=yarn'},
  {id:'hd14',subj:'Hadoop',lvl:'B',item:'hadoop-env.sh→JAVA_HOME。slaves→DataNode节点列表。SSH免密登录避免启动输密码'},
  {id:'hd15',subj:'Hadoop',lvl:'B',item:'HA高可用：Active+Standby双NameNode，ZooKeeper故障切换，JournalNode同步edits日志'},
  {id:'hd16',subj:'Hadoop',lvl:'B',item:'Federation：多个NameNode各自管理部分目录，解决单点内存瓶颈'},
  {id:'hd17',subj:'Hadoop',lvl:'B',item:'MapReduce序列化：Writable接口(Hadoop自定义，比Java序列化紧凑)。Text对应String、IntWritable对应int'},
  {id:'hd18',subj:'Hadoop',lvl:'B',item:'Partitioner分区器：决定Map输出去哪个Reduce，默认HashPartitioner(hash%reduce数)。可自定义继承Partitioner'},
  {id:'hd19',subj:'Hadoop',lvl:'B',item:'Combiner：Map端局部聚合(类似小Reduce)，减少网络传输量。必须和Reduce逻辑一致才能用'},
  {id:'hd20',subj:'Hadoop',lvl:'B',item:'hdfs dfs -moveFromLocal上传后删本地、-copyFromLocal上传保留本地、-appendToFile追加内容'},
  {id:'hd21',subj:'Hadoop',lvl:'B',item:'namenode -format格式化NameNode(仅首次！多次format会丢数据)。jps验证进程(5个：NN/DN/RM/NM/SNN)'},
  {id:'hd22',subj:'Hadoop',lvl:'B',item:'HDFS一次写入多次读取：不支持并发写入、不支持随机修改、只支持追加。适合批处理不适合实时'},
  {id:'hd23',subj:'Hadoop',lvl:'C',item:'Hadoop生态：Hive(数据仓库SQL)、HBase(NoSQL实时)、Flume(日志采集)、Sqoop(数据导入导出)'},
  {id:'hd24',subj:'Hadoop',lvl:'C',item:'Hadoop jar提交MR任务。yarn application -list查看运行应用、-kill终止应用、-status查看状态'},
  {id:'hd25',subj:'Hadoop',lvl:'C',item:'InputSplit决定Map并行度(默认=Block数)。RecordReader将Split内容转为key-value对'},
  {id:'hd26',subj:'Hadoop',lvl:'B',item:'Shuffle四步：分区Partition→排序Sort→合并Combine→归并Merge。涉及磁盘IO和网络传输'},
  {id:'hd27',subj:'Hadoop',lvl:'C',item:'默认YARN Web端口8088、HDFS NameNode Web端口50070(2.x)/9870(3.x)'},
  {id:'hd28',subj:'Hadoop',lvl:'C',item:'启动集群：start-dfs.sh启动HDFS→start-yarn.sh启动YARN。或start-all.sh(已废弃但考试可能考)'},
  {id:'hd29',subj:'Hadoop',lvl:'C',item:'SecondaryNameNode不是热备！它的作用是定期从NameNode拉取edits并合并到fsimage，减轻NN重启压力'},
  {id:'hd30',subj:'Hadoop',lvl:'C',item:'MapReduce计数器Counter用于统计。Reducer数量通过job.setNumReduceTasks()设置，默认=1'},
  {id:'hd31',subj:'Hadoop',lvl:'C',item:'hdfs dfsadmin -report查看集群状态、hdfs fsck /检查文件系统健康、hdfs dfs -du统计目录大小'},
  {id:'hd32',subj:'Hadoop',lvl:'B',item:'DataNode心跳：每3秒向NameNode发送心跳+块报告，10分钟未收到心跳认为宕机'},
  {id:'hd33',subj:'Hadoop',lvl:'C',item:'Hadoop三大核心组件：HDFS(分布式文件系统)+MapReduce(分布式计算)+YARN(资源管理)'},
  {id:'hd34',subj:'Hadoop',lvl:'C',item:'WritableComparable接口=Writable(序列化)+Comparable(排序)。作为Map输出key时需实现该接口'},
  {id:'hd35',subj:'Hadoop',lvl:'B',item:'FileInputFormat设置输入路径、FileOutputFormat设置输出路径(目录不能已存在！否则报错)'},

  // ==================== Scala & Spark (30条) ====================
  {id:'ss01',subj:'Scala & Spark',lvl:'A',item:'var可重新赋值(变量)、val不可重新赋值(常量/final)。推荐用val(函数式风格)'},
  {id:'ss02',subj:'Scala & Spark',lvl:'A',item:'Tuple元组：最大22个元素，t._1 t._2访问(索引从1开始！不是0)。创建后不可修改'},
  {id:'ss03',subj:'Scala & Spark',lvl:'A',item:'Array定长同类型(Array(1,2,3))、ArrayBuffer变长可增删、List默认不可变有序、Set无序不重复、Map键值对'},
  {id:'ss04',subj:'Scala & Spark',lvl:'A',item:'方法用def定义(def add(a:Int):Int={a+b})，函数是对象可赋值(val f=(a:Int)=>a+1)'},
  {id:'ss05',subj:'Scala & Spark',lvl:'A',item:'RDD=弹性分布式数据集。五大属性：分区列表/计算函数/依赖关系/分区器(可选)/优先位置。基于内存不可变'},
  {id:'ss06',subj:'Scala & Spark',lvl:'A',item:'Transformation惰性求值：map/filter/flatMap/reduceByKey/groupByKey/sortBy。Action触发计算：count/collect/reduce/foreach/saveAsTextFile'},
  {id:'ss07',subj:'Scala & Spark',lvl:'A',item:'宽窄依赖：窄(一对一不Shuffle)如map/filter/flatMap。宽(一对多Shuffle)如reduceByKey/join。宽依赖划分Stage'},
  {id:'ss08',subj:'Scala & Spark',lvl:'A',item:'SparkSession(Spark2.0+统一入口)。DataFrame=Dataset[Row]有Schema。DataSet强类型编译安全'},
  {id:'ss09',subj:'Scala & Spark',lvl:'A',item:'Spark两种分析方式：API(select/filter/groupBy)和视图+SQL(createOrReplaceTempView+spark.sql)'},
  {id:'ss10',subj:'Scala & Spark',lvl:'A',item:'RDD编程模板：SparkConf→SparkContext→textFile→flatMap→map→reduceByKey→saveAsTextFile→sc.stop()'},
  {id:'ss11',subj:'Scala & Spark',lvl:'A',item:'Spark比MapReduce快10~100倍：基于内存迭代计算，避免磁盘IO。MR每次Job结果都写磁盘'},
  {id:'ss12',subj:'Scala & Spark',lvl:'A',item:'Spark架构：Driver(main程序)→Executor(JVM执行Task)。Master/Worker(Standalone模式)。1Drv+NExec'},
  {id:'ss13',subj:'Scala & Spark',lvl:'B',item:'四种运行模式：Local(local[*])、Standalone(自带)、YARN(生产常用)、Mesos/K8s'},
  {id:'ss14',subj:'Scala & Spark',lvl:'B',item:'Spark组件选型：SQL/报表→Spark SQL、实时流→Spark Streaming、机器学习→MLlib、图计算→GraphX'},
  {id:'ss15',subj:'Scala & Spark',lvl:'B',item:'Scala面向对象：class多例、object单例、extends继承、override重写(必须写)、trait特质(多重with)'},
  {id:'ss16',subj:'Scala & Spark',lvl:'B',item:'for(i<-1 to 5)含5、for(i<-1 until 5)不含5。可加if守卫、yield生成新集合'},
  {id:'ss17',subj:'Scala & Spark',lvl:'B',item:'Catalyst查询优化器：Spark SQL核心，谓词下推+列裁剪+物理计划优化。比直接RDD代码快'},
  {id:'ss18',subj:'Scala & Spark',lvl:'B',item:'Parquet是Spark SQL默认文件格式(列式存储高压缩比)。支持JSON/CSV/JDBC/Hive等多种数据源'},
  {id:'ss19',subj:'Scala & Spark',lvl:'B',item:'SaveMode四种：ErrorIfExists(默认报错)、Append追加、Overwrite覆盖、Ignore忽略'},
  {id:'ss20',subj:'Scala & Spark',lvl:'B',item:'Spark分区：HashPartitioner默认、自定义需继承Partitioner重写numPartitions和getPartition'},
  {id:'ss21',subj:'Scala & Spark',lvl:'C',item:'RDD持久化：cache()→默认MEMORY_ONLY。persist()可选多种级别(MEMORY_AND_DISK等)。血缘Lineage容错'},
  {id:'ss22',subj:'Scala & Spark',lvl:'C',item:'广播变量Broadcast(只读共享)和累加器Accumulator(只写聚合)。解决闭包传大变量问题'},
  {id:'ss23',subj:'Scala & Spark',lvl:'B',item:'flatMap先map再flat扁平化：flatMap(_.split(" "))是WordCount经典用法。和map区别：map返回嵌套'},
  {id:'ss24',subj:'Scala & Spark',lvl:'C',item:'spark-shell自动提供spark(SparkSession)和sc(SparkContext)。需导入spark.implicits._'},
  {id:'ss25',subj:'Scala & Spark',lvl:'C',item:'Scala主构造器执行类体中所有代码(除方法和辅助构造器)。辅助构造器def this()第一行必须调主构造器'},
  {id:'ss26',subj:'Scala & Spark',lvl:'B',item:'::用于List拼接(1::2::Nil→List(1,2))。:::拼接两个List。++通用拼接。Nil空列表'},
  {id:'ss27',subj:'Scala & Spark',lvl:'C',item:'模式匹配match case：类似Java switch但更强大，可匹配类型/提取器/守卫条件'},
  {id:'ss28',subj:'Scala & Spark',lvl:'B',item:'DataFrame常用操作：show()显示、printSchema()打印结构、select()选列、filter()过滤、groupBy()分组'},
  {id:'ss29',subj:'Scala & Spark',lvl:'C',item:'Spark读取文件：spark.read.format("json").load(path)或直接用spark.read.json/csv/jdbc'},
  {id:'ss30',subj:'Scala & Spark',lvl:'C',item:'Scala安装Windows：设SCALA_HOME、PATH加%SCALA_HOME%\\bin。CMD输入scala进交互模式即成功'},

  // ==================== HBase / ZooKeeper (25条) ====================
  {id:'hz01',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase架构：HMaster(主节点Region管理)、RegionServer(从节点读写)、ZooKeeper(选举+元数据)。底层HDFS'},
  {id:'hz02',subj:'HBase / ZooKeeper',lvl:'A',item:'ZK集群2n+1台(奇数)。过半机制：>半数同意才选出Leader。允许n台失效。myid标识节点ID'},
  {id:'hz03',subj:'HBase / ZooKeeper',lvl:'A',item:'ZNode最大1MB。四种类型：持久/临时/持久顺序/临时顺序。ls查看子节点，get获取数据'},
  {id:'hz04',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase数据模型：RowKey(字典序设计关键)+Column Family(列族)+Timestamp(版本)+Cell(RowKey+CF+列+TS)'},
  {id:'hz05',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase特点：列式存储、稀疏性(空列不占空间)、易扩展、PB级海量存储、高并发随机读写。全称Hadoop Database'},
  {id:'hz06',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase参考Google Bigtable设计。底层存储HDFS。面向列族设计。NameSpace默认default'},
  {id:'hz07',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase Shell：create建表、put插入、get获取单行、scan扫描、delete删除、disable+drop删表、list列出'},
  {id:'hz08',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase Java API：HBaseConfiguration.create()→ConnectionFactory→Table→Put/Get/Scan→Result。操作完close()'},
  {id:'hz09',subj:'HBase / ZooKeeper',lvl:'B',item:'大数据4V：Volume大量、Velocity高速、Variety多样、Value价值密度低(不是高！)←考试陷阱'},
  {id:'hz10',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase读流程：Client→ZK获取meta表位置→找RegionServer→先MemStore再StoreFile(HFile)'},
  {id:'hz11',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase写流程：先写WAL(HLog预写日志)→写MemStore内存→MemStore满了Flush到StoreFile(HFile)'},
  {id:'hz12',subj:'HBase / ZooKeeper',lvl:'B',item:'Region是HBase分布式存储的最小单元。一张表水平切分为多个Region。每个Region有startRow和endRow'},
  {id:'hz13',subj:'HBase / ZooKeeper',lvl:'B',item:'Store=一个列族在一个Region内的存储。包含一个MemStore+多个StoreFile(HFile)。刷写Flush→合并Compaction'},
  {id:'hz14',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase配置：hbase-site.xml(hbase.cluster.distributed、hbase.zookeeper.quorum)、hbase-env.sh(HBASE_MANAGES_ZK)'},
  {id:'hz15',subj:'HBase / ZooKeeper',lvl:'C',item:'ZK选举：先投自己→比较myid→票数过半胜出→选为Leader→其余Follower。广播机制同步状态'},
  {id:'hz16',subj:'HBase / ZooKeeper',lvl:'C',item:'HMaster Web默认端口16010(1.x+)。HBASE_MANAGES_ZK=false使用外部ZooKeeper集群'},
  {id:'hz17',subj:'HBase / ZooKeeper',lvl:'C',item:'HBase不支持事务、不支持SQL查询、不支持二级索引(需Phoenix等第三方)。RowKey设计是关键'},
  {id:'hz18',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase修改数据=插入新版本(同RowKey+新Timestamp)。HBase不真正修改或删除数据(标记删除)'},
  {id:'hz19',subj:'HBase / ZooKeeper',lvl:'C',item:'HBase与RDBMS区别：HBase分布式列式NoSQL、无Schema灵活、横向扩展。RDBMS单机行式ACID事务'},
  {id:'hz20',subj:'HBase / ZooKeeper',lvl:'C',item:'Put.addColumn(列族,列,值)插入。Get.addColumn/Get.addFamily获取。Scan.setStartRow/StopRow扫描范围'},
  {id:'hz21',subj:'HBase / ZooKeeper',lvl:'C',item:'Compaction合并StoreFile：Minor合并少量、Major合并全部(清理过期数据)。Region Split自动切分Region'},
  {id:'hz22',subj:'HBase / ZooKeeper',lvl:'C',item:'Windows开发需winutils.exe+hadoop.dll。pom.xml添加hbase-client依赖'},
  {id:'hz23',subj:'HBase / ZooKeeper',lvl:'B',item:'ZK应用场景：配置管理、命名服务、分布式锁、集群管理、选举。HBase用ZK做HMaster选举和meta表定位'},
  {id:'hz24',subj:'HBase / ZooKeeper',lvl:'C',item:'HBase表预分区：创建表时指定split keys，避免热点Region。盐值(Salting)打散RowKey分布'},
  {id:'hz25',subj:'HBase / ZooKeeper',lvl:'C',item:'HBase过滤器Filter：RowFilter/ColumnPrefixFilter/ValueFilter等。Scan.setFilter()设置。减少不必要数据传输'},

  // ==================== Web前端 (25条) ====================
  {id:'wf01',subj:'Web前端',lvl:'A',item:'HTML结构：<html><head>(元数据/样式/标题)<body>(可见内容)。<!DOCTYPE html>声明HTML5'},
  {id:'wf02',subj:'Web前端',lvl:'A',item:'常用标签：<a>链接href、<img>图片src/alt、<div>块级、<span>行内、<h1>-<h6>标题、<p>段落、<br>换行'},
  {id:'wf03',subj:'Web前端',lvl:'A',item:'表单：<form>+<input>。type：text/password/submit/radio/checkbox/email。<textarea>多行<select>下拉。name传参'},
  {id:'wf04',subj:'Web前端',lvl:'A',item:'表格：<table><tr><td>。<th>表头粗体居中。border/cellspacing/cellpadding属性'},
  {id:'wf05',subj:'Web前端',lvl:'A',item:'CSS选择器：#id(权重100)、.class(权重10)、标签(权重1)、*通配(0)。优先级!important>行内>id>class>标签'},
  {id:'wf06',subj:'Web前端',lvl:'A',item:'CSS盒模型：content+padding+border+margin。box-sizing:border-box(含b+p)vs content-box(仅w)。border-box更直观'},
  {id:'wf07',subj:'Web前端',lvl:'A',item:'CSS定位：static默认/relative相对偏移/absolute定位祖先/fixed固定视口/sticky粘性。relative占空间'},
  {id:'wf08',subj:'Web前端',lvl:'A',item:'display：block独占宽高/inline不换行/inline-block可设宽高/none隐藏不占。flex/grid布局'},
  {id:'wf09',subj:'Web前端',lvl:'A',item:'居中：水平margin:0 auto(块级需宽)/text-align:center(行内)。垂直flex(align-items:center)/line-height'},
  {id:'wf10',subj:'Web前端',lvl:'A',item:'JS变量：var(函数/提升)、let(块/TDZ)、const(块/不可重新赋值)。推荐const→let，不用var'},
  {id:'wf11',subj:'Web前端',lvl:'A',item:'DOM操作：getElementById(id)→单个、querySelector→单个、querySelectorAll→NodeList。innerHTML读写内容'},
  {id:'wf12',subj:'Web前端',lvl:'B',item:'JS数据类型：基本(number/string/boolean/null/undefined)、引用(object/array)。typeof null→object(bug)'},
  {id:'wf13',subj:'Web前端',lvl:'B',item:'事件：onclick/onsubmit/onload/onchange/onmouseover。绑定：onclick=fn或addEventListener。表单onsubmit验证'},
  {id:'wf14',subj:'Web前端',lvl:'B',item:'CSS引入：行内style(最高)>内嵌<style>(中)>外部<link>(低)。!important打破规则'},
  {id:'wf15',subj:'Web前端',lvl:'B',item:'HTML5语义化：<header>/<nav>/<main>/<article>/<section>/<aside>/<footer>。替代无意义div'},
  {id:'wf16',subj:'Web前端',lvl:'B',item:'Float浮动：left/right脱离文档流。父容器塌陷。清除：clear:both/overflow:hidden/::after(clearfix)'},
  {id:'wf17',subj:'Web前端',lvl:'B',item:'Flexbox：display:flex。容器justify-content/align-items/flex-direction。项目flex比例/align-self'},
  {id:'wf18',subj:'Web前端',lvl:'C',item:'响应式：@media(max-width:768px){}。移动优先。viewport:width=device-width'},
  {id:'wf19',subj:'Web前端',lvl:'B',item:'表单验证：required必填/pattern正则/type="email"/min/max。JS:onsubmit中return false阻止提交'},
  {id:'wf20',subj:'Web前端',lvl:'B',item:'CSS文本属性：font-size/font-family/font-weight/color/background/border/text-align/line-height'},
  {id:'wf21',subj:'Web前端',lvl:'C',item:'CSS Grid二维布局：grid-template-columns定义列、gap间距。比Flexbox更适合复杂网格布局'},
  {id:'wf22',subj:'Web前端',lvl:'C',item:'JS数组方法：map/filter/reduce/forEach/find/sort。map返回新数组不改变原数组'},
  {id:'wf23',subj:'Web前端',lvl:'C',item:'AJAX异步请求：XMLHttpRequest或fetch()。不刷新页面与服务器通信。JSON格式数据交换'},
  {id:'wf24',subj:'Web前端',lvl:'C',item:'ES6新特性：箭头函数()=>{}、模板字符串`${}`、解构赋值{}=obj、展开运算符...、Promise异步'},
  {id:'wf25',subj:'Web前端',lvl:'C',item:'CSS3动画：transition过渡(属性/时长/缓动)、@keyframes+animation关键帧动画、transform变换旋转缩放'},
];
