// 五科完整知识清单 — 从588道真题 + 课件 + 考点分析中全面提炼（v2）
const CHECKLIST = [
  // ==================== Java Web (58条) ====================
  {id:'jw001',subj:'Java Web',lvl:'A',item:'C/S(客户端/服务器)和B/S(浏览器/服务器)的定义与区别：C/S需安装客户端、B/S浏览器直接访问'},
  {id:'jw002',subj:'Java Web',lvl:'B',item:'JSP的本质：能写Java代码的HTML页面，最终被翻译成Servlet'},
  {id:'jw003',subj:'Java Web',lvl:'A',item:'JSP运行流程四步：客户端请求→JSP转译成Servlet源码→编译成.class→执行响应。再次请求直接用.class'},
  {id:'jw004',subj:'Java Web',lvl:'A',item:'JSP 9大隐式对象背诵：request, response, session, application, config, out, page, pageContext, exception'},
  {id:'jw005',subj:'Java Web',lvl:'A',item:'request对象：HttpServletRequest类型，getParameter()获取单值、getParameterValues()获取多值、getParameterNames()获取所有参数名'},
  {id:'jw006',subj:'Java Web',lvl:'A',item:'response对象：sendRedirect()重定向、addCookie()添加Cookie、setContentType()设置响应类型'},
  {id:'jw007',subj:'Java Web',lvl:'A',item:'session对象：服务器端会话跟踪，setAttribute()/getAttribute()存取数据，一次会话内有效'},
  {id:'jw008',subj:'Java Web',lvl:'B',item:'application对象(ServletContext)：整个Web应用共享，所有用户都能访问，通过getServletContext()获取'},
  {id:'jw009',subj:'Java Web',lvl:'A',item:'四大作用域从小到大：page(本页) < request(一次请求) < session(一次会话) < application(整个应用)'},
  {id:'jw010',subj:'Java Web',lvl:'B',item:'pageContext对象：可以获取其他8个隐式对象，管理不同作用域的属性'},
  {id:'jw011',subj:'Java Web',lvl:'B',item:'out对象：JspWriter类型，向页面输出内容；page对象：当前JSP页面对应的Servlet类实例(this)'},
  {id:'jw012',subj:'Java Web',lvl:'B',item:'exception对象：仅isErrorPage="true"的页面可用，Throwable类型，表示异常信息'},
  {id:'jw013',subj:'Java Web',lvl:'A',item:'三种JSP脚本元素：<% 脚本片段 %>写Java逻辑、<%= 表达式 %>输出结果、<%! 声明 %>定义成员变量/方法'},
  {id:'jw014',subj:'Java Web',lvl:'A',item:'三种JSP指令：page指令(导包/编码/错误页)、include指令(编译时包含)、taglib指令(引入JSTL等标签库)'},
  {id:'jw015',subj:'Java Web',lvl:'A',item:'include指令 vs include动作：编译时合并源码(改后需重编译) vs 运行时合并HTML结果(改后直接生效+可传参)'},
  {id:'jw016',subj:'Java Web',lvl:'B',item:'page指令常用属性：import(导包)、pageEncoding(页面编码)、contentType(响应类型)、errorPage(错误页)、isErrorPage(是否错误页)'},
  {id:'jw017',subj:'Java Web',lvl:'A',item:'JSP动作标签三剑客：<jsp:useBean id="x" class="包.类" scope="session"/>创建对象、<jsp:setProperty>设值、<jsp:getProperty>取值'},
  {id:'jw018',subj:'Java Web',lvl:'A',item:'JavaBean规范：public类+private属性+public的getter/setter+无参构造方法；boolean类型用isXxx()代替getXxx()'},
  {id:'jw019',subj:'Java Web',lvl:'B',item:'EL表达式入门：${name}取session属性、${user.name}取JavaBean属性、${map.key}取Map值、${3+5}可做运算'},
  {id:'jw020',subj:'Java Web',lvl:'A',item:'JSTL核心标签：<c:if test="条件">单分支(无else！)、<c:choose>/<c:when>/<c:otherwise>多分支、<c:forEach items items="集合" var="变量">循环、<c:set>设变量'},
  {id:'jw021',subj:'Java Web',lvl:'A',item:'JDBC四步走：①Class.forName("驱动类")加载驱动→②DriverManager.getConnection(url,user,pwd)获取连接→③Statement/PreparedStatement执行SQL→④关闭ResultSet→Statement→Connection'},
  {id:'jw022',subj:'Java Web',lvl:'A',item:'Servlet生命周期三阶段：init()初始化(调1次)→service()/doGet()/doPost()每次请求调→destroy()销毁时调'},
  {id:'jw023',subj:'Java Web',lvl:'A',item:'ServletConfig vs ServletContext区别：Config是单个Servlet的配置(仅自己用)、Context是整个Web应用的配置(所有Servlet共享)；获取方式不同'},
  {id:'jw024',subj:'Java Web',lvl:'A',item:'Filter过滤器：实现javax.servlet.Filter接口，三个方法init(FilterConfig)→doFilter(req,resp,chain)→destroy()'},
  {id:'jw025',subj:'Java Web',lvl:'A',item:'Filter关键点：doFilter中必须调用chain.doFilter(req,resp)放行，否则请求被拦截；多个Filter按web.xml注册顺序执行'},
  {id:'jw026',subj:'Java Web',lvl:'B',item:'FilterConfig接口方法：getServletContext()、getInitParameter(name)、getFilterName()、getInitParameterNames()'},
  {id:'jw027',subj:'Java Web',lvl:'A',item:'请求转发(forward) vs 重定向(sendRedirect)：URL不变/变、1次/2次请求、能/不能共享request数据、不能/能跨域、快/慢'},
  {id:'jw028',subj:'Java Web',lvl:'A',item:'转发代码：request.getRequestDispatcher("url").forward(req,resp)；重定向代码：response.sendRedirect("url")'},
  {id:'jw029',subj:'Java Web',lvl:'A',item:'MVC三层模式：Model(JavaBean/Dao-数据与业务逻辑)、View(JSP-页面展示)、Controller(Servlet-调度控制)'},
  {id:'jw030',subj:'Java Web',lvl:'A',item:'MVC登录代码模板(必默写)：login.jsp→LoginServlet(获取参数→调Dao验证→成功redirect/失败forward+设errorMsg)→web.xml配置映射'},
  {id:'jw031',subj:'Java Web',lvl:'A',item:'web.xml配置Servlet：一对标签<servlet>(servlet-name+servlet-class)和<servlet-mapping>(servlet-name+url-pattern)'},
  {id:'jw032',subj:'Java Web',lvl:'A',item:'Session vs Cookie五点区别：①存放位置(服务器/浏览器)②安全性(安全/不安全)③服务器压力(有/无)④容量(无限制/≤4KB)⑤用途(重要信息/偏好)'},
  {id:'jw033',subj:'Java Web',lvl:'B',item:'Cookie操作：new Cookie(name,value)创建→setMaxAge(秒)设置有效期→response.addCookie()发送到客户端'},
  {id:'jw034',subj:'Java Web',lvl:'B',item:'Tomcat核心知识：默认端口8080、配置文件server.xml在conf目录、WEB-INF目录下文件浏览器不可直接访问、work目录存编译后的Servlet类文件'},
  {id:'jw035',subj:'Java Web',lvl:'B',item:'编码三处统一UTF-8：JSP的pageEncoding="UTF-8"、request.setCharacterEncoding("UTF-8")、response.setContentType("text/html;charset=UTF-8")'},
  {id:'jw036',subj:'Java Web',lvl:'B',item:'HTTP状态码：200成功、302重定向(sendRedirect触发)、404未找到、500服务器内部错误'},
  {id:'jw037',subj:'Java Web',lvl:'B',item:'GET vs POST：GET参数在URL后面可见(不安全、长度限制)、POST参数在请求体中(安全、无长度限制) — 登录/上传用POST'},
  {id:'jw038',subj:'Java Web',lvl:'B',item:'@WebServlet注解：Servlet 3.0+可用@WebServlet("/url")替代web.xml中的<servlet>+<servlet-mapping>配置'},
  {id:'jw039',subj:'Java Web',lvl:'B',item:'Servlet继承体系：Servlet接口→GenericServlet抽象类(实现Servlet+ServletConfig)→HttpServlet(处理HTTP请求，重写doGet/doPost)'},
  {id:'jw040',subj:'Java Web',lvl:'B',item:'HttpServletRequest常用方法：getParameter()、getParameterValues()、getParameterNames()、getRemoteAddr()、getMethod()、getRequestURI()'},
  {id:'jw041',subj:'Java Web',lvl:'B',item:'域对象通用方法：setAttribute(key,val)存、getAttribute(key)取、removeAttribute(key)删、getAttributeNames()遍历 — 四大作用域通用'},
  {id:'jw042',subj:'Java Web',lvl:'C',item:'Tomcat部署方式：war包放webapps目录自动解压、项目文件夹直接放webapps、通过server.xml配置<Context>'},
  {id:'jw043',subj:'Java Web',lvl:'C',item:'Web应用目录结构：根目录/WEB-INF/web.xml(部署描述符)、/WEB-INF/classes(编译后类文件)、/WEB-INF/lib(依赖jar包)'},

  // ==================== Linux (48条) ====================
  {id:'lx001',subj:'Linux',lvl:'A',item:'文件目录操作：ls -a(含隐藏) ls -l(详细信息) ls -d(目录本身)、cd(切换~回家)、pwd(当前路径)、mkdir -p(递归建目录)、rmdir(删空目录)'},
  {id:'lx002',subj:'Linux',lvl:'A',item:'文件增删改查：touch(建空文件/更新时间戳)、cp(复制)、mv(移动/同目录=重命名)、rm(删除) rm -r(递归删) rm -f(强制删)'},
  {id:'lx003',subj:'Linux',lvl:'A',item:'文件查看：cat(全部输出/合并) cat f1>f2(复制)、more(单向分页)、less(双向分页可搜索)、head -n(前n行默认10)、tail -n(后n行) tail -f(实时跟踪)'},
  {id:'lx004',subj:'Linux',lvl:'B',item:'文件分析：file(判断类型)、wc(统计行/单词/字符数 wc -l行数)、find(查找文件)、locate(快速定位)、which(查找命令位置)'},
  {id:'lx005',subj:'Linux',lvl:'A',item:'权限管理-chmod数字：r=4 w=2 x=1；7=rwx 6=rw- 5=r-x 4=r--；chmod 755(rwxr-xr-x)最常用、chmod 764(rwxrw-r--)考题高频'},
  {id:'lx006',subj:'Linux',lvl:'A',item:'权限管理-chmod符号：u(user) g(group) o(other) a(all)；+加权限 -减权限 =设权限；chmod u+x加执行、chmod a-x全去执行'},
  {id:'lx007',subj:'Linux',lvl:'B',item:'chown改变文件所有者(只有root能做)、chgrp改变文件所属组、umask设置默认权限掩码'},
  {id:'lx008',subj:'Linux',lvl:'A',item:'vi/vim三种模式：命令模式(默认)↔插入模式(i光标前/a光标后/o下一行/O上一行)↔末行模式(:wq保存退出/:q!不保存退出)'},
  {id:'lx009',subj:'Linux',lvl:'A',item:'vi/vim常用命令：dd删一行、yy复制一行、p粘贴、u撤销、.重复上一步、nG跳到第n行、/搜索、:set nu显示行号 :set nonu隐藏行号'},
  {id:'lx010',subj:'Linux',lvl:'A',item:'Shell变量：赋值等号两边无空格(变量名=值)、引用用$变量名或${变量名}、只读变量readonly、删除变量unset'},
  {id:'lx011',subj:'Linux',lvl:'A',item:'Shell脚本：首行#!/bin/bash、注释用#、$0脚本名 $#参数个数 $1/$2第N个参数 $?上条命令退出状态 $@所有参数 $*所有参数(字符串)'},
  {id:'lx012',subj:'Linux',lvl:'B',item:'Shell引号区别：单引号(全部原样输出不解释变量)、双引号(解释变量和命令替换)、反引号或$()(命令替换执行命令返回结果)'},
  {id:'lx013',subj:'Linux',lvl:'B',item:'Shell流程控制：if [条件];then...elif...else...fi、for i in列表;do...done、while [条件];do...done、case $var in 模式)...;;esac'},
  {id:'lx014',subj:'Linux',lvl:'B',item:'Shell条件判断：数值(-eq=-eq -ne≠ -gt> -ge≥ -lt< -le≤)、字符串(=相等 !=不等 -z空串 -n非空)、文件(-f普通文件 -d目录 -e存在 -r可读 -w可写 -x可执行)'},
  {id:'lx015',subj:'Linux',lvl:'A',item:'tar压缩/解压：tar -zcvf压缩(.tar.gz)、tar -xzvf解压、tar -C /path指定解压目录、tar -tf查看包内容；z=gzip压缩 c=创建 x=解压 v=显示 f=文件名'},
  {id:'lx016',subj:'Linux',lvl:'B',item:'grep文本搜索：grep "关键词" 文件、-i忽略大小写、-v反向(不含)、-n显示行号、-r递归、-c计数、支持正则. * ^ $ [] [^]'},
  {id:'lx017',subj:'Linux',lvl:'A',item:'管道与重定向：|管道(前命令输出作后命令输入)、>覆盖重定向、>>追加重定向、<输入重定向、2>错误重定向、2>&1错误合并到标准输出、/dev/null黑洞'},
  {id:'lx018',subj:'Linux',lvl:'A',item:'进程管理：ps -aux(查看全部进程)、ps -ef(另一种格式)、top(实时监控)、kill PID(终止进程)、kill -9 PID(强杀)、killall 进程名(终止所有同名)、bg/fg(后/前台)'},
  {id:'lx019',subj:'Linux',lvl:'A',item:'用户管理：useradd创建(-d指定家目录)、passwd设密码、usermod修改(不能删用户！)、userdel删除(-r同时删主目录)、su切换用户(su -加载环境)、sudo提权'},
  {id:'lx020',subj:'Linux',lvl:'B',item:'用户与组：/etc/passwd(用户信息)、/etc/shadow(密码信息)、/etc/group(组信息)；groupadd建组、gpasswd管理组成员、id查看用户uid/gid'},
  {id:'lx021',subj:'Linux',lvl:'B',item:'软硬链接：ln -s创建软链接(快捷方式、删原文件失效、可跨文件系统)、ln创建硬链接(共享i节点、删原文件仍可用、不能跨文件系统、不能链接目录)'},
  {id:'lx022',subj:'Linux',lvl:'A',item:'Linux目录结构(FHS标准)：/bin基本命令 /sbin系统管理 /etc配置 /home用户家 /root超级用户家 /boot内核 /dev设备 /tmp临时 /var日志 /usr用户程序 /opt第三方'},
  {id:'lx023',subj:'Linux',lvl:'B',item:'磁盘管理：df -h(查看磁盘使用)、du -sh(查看目录/文件大小)、mount(挂载)、umount(卸载)、fdisk -l(查看磁盘分区)'},
  {id:'lx024',subj:'Linux',lvl:'B',item:'网络命令：ping测试连通、ifconfig/ip addr查看IP、netstat -tlnp查看监听端口、ssh远程登录、scp远程拷贝、curl/wget下载文件'},
  {id:'lx025',subj:'Linux',lvl:'B',item:'环境变量：export设置(如export PATH=$PATH:/new)、env查看所有、~/.bashrc或/etc/profile配置永久生效；source命令使配置立即生效'},
  {id:'lx026',subj:'Linux',lvl:'B',item:'关机重启：shutdown -h now(立即关机)/+30(30分钟后)/12:30(定时)、shutdown -c取消、shutdown -r now重启、halt关机、reboot重启、poweroff断电'},
  {id:'lx027',subj:'Linux',lvl:'B',item:'FTP端口：20(数据传输)+21(控制连接)；SSH端口22；HTTP端口80；HTTPS端口443；MySQL端口3306'},
  {id:'lx028',subj:'Linux',lvl:'C',item:'文本处理三剑客：grep(搜索过滤)、sed(流编辑器-查找替换)、awk(文本分析-按列处理)；sort排序 uniq去重 cut截取 tr字符转换'},
  {id:'lx029',subj:'Linux',lvl:'C',item:'文件系统与i节点：ext3/ext4文件名最长255字符；i节点(inode)存文件元数据(大小/权限/时间/数据块指针)；一个文件一个i节点，硬链接共享i节点'},
  {id:'lx030',subj:'Linux',lvl:'C',item:'运行级别(runlevel)：0关机 1单用户 2多用户(无NFS) 3完全多用户(命令行) 4未使用 5图形界面 6重启；查看runlevel或who -r'},

  // ==================== Hadoop (35条) ====================
  {id:'hd001',subj:'Hadoop',lvl:'A',item:'Hadoop三大核心组件：HDFS(分布式存储)+YARN(资源调度)+MapReduce(分布式计算)'},
  {id:'hd002',subj:'Hadoop',lvl:'A',item:'NameNode职责：管理元数据(文件目录树、Block→DataNode映射、权限)，所有元数据在内存中(所以大内存！)，不存实际数据'},
  {id:'hd003',subj:'Hadoop',lvl:'A',item:'DataNode职责：存储实际数据块(Block)，定期(默认3秒)向NameNode发送心跳和块报告，心跳超时10分钟标记为死亡'},
  {id:'hd004',subj:'Hadoop',lvl:'A',item:'SecondaryNameNode：定期合并fsimage(元数据快照)和edits(操作日志)生成新fsimage，不是NameNode的热备/备份！只辅助恢复'},
  {id:'hd005',subj:'Hadoop',lvl:'A',item:'Block核心参数：HDFS2.x默认128MB、副本数默认3(通过dfs.replication配置)；500MB文件=4个Block(128×3+116×1)在NameNode占用4条元数据'},
  {id:'hd006',subj:'Hadoop',lvl:'A',item:'副本放置策略(机架感知Rack Awareness)：第1个副本存客户端所在节点(或随机)、第2个存不同机架、第3个存同机架不同节点；目标是容错+带宽优化'},
  {id:'hd007',subj:'Hadoop',lvl:'A',item:'HDFS不适合存大量小文件(简答高频)：①NameNode元数据内存压力(每个文件一条元数据≈150字节)②一个Block最小占一个Block浪费空间③MapReduce一个文件一个Map任务开销大；解决方案：合并/SequenceFile/HBase/Har归档'},
  {id:'hd008',subj:'Hadoop',lvl:'A',item:'HDFS写数据流程(7步)：Client→NameNode请求→NameNode检查+返回DataNode列表→Client向第一个DN写→DN间Pipeline管道传输→全部写完返回ack→NameNode更新元数据'},
  {id:'hd009',subj:'Hadoop',lvl:'A',item:'HDFS常用命令：hdfs dfs -mkdir -p(建目录)、-put(上传)、-get(下载)、-ls -R(递归列出)、-cat(查看)、-rm -r(递归删)、-getmerge(合并下载)、-moveFromLocal(移动上传)、-copyFromLocal(复制上传)、-cp(复制)、-mv(移动)'},
  {id:'hd010',subj:'Hadoop',lvl:'B',item:'HDFS HA(高可用)：Active+Standby双NameNode、ZooKeeper监控故障自动切换、共享edits日志(通过JournalNode Quorum)、避免单点故障'},
  {id:'hd011',subj:'Hadoop',lvl:'C',item:'HDFS Federation(联邦)：多个独立NameNode各管一部分命名空间(如/user、/data分开)、解决单NameNode内存瓶颈、NameNode之间相互独立'},
  {id:'hd012',subj:'Hadoop',lvl:'A',item:'YARN全称Yet Another Resource Negotiator、核心组件：ResourceManager(全局资源调度大老板)、NodeManager(每节点资源管理)、ApplicationMaster(应用资源申请项目经理)、Container(CPU+Memory最小资源单位)'},
  {id:'hd013',subj:'Hadoop',lvl:'A',item:'YARN工作流程：Client提交作业→RM分配Container启动AM→AM向RM申请资源→RM以Container形式分配→AM在Container中启动Map/Reduce任务→执行完毕释放资源'},
  {id:'hd014',subj:'Hadoop',lvl:'B',item:'YARN调度器三种：FIFO(先进先出-简单但可能阻塞)、Capacity(容量-多队列保证最小资源)、Fair(公平-动态均衡分配资源)'},
  {id:'hd015',subj:'Hadoop',lvl:'A',item:'MapReduce执行流程六步：Input输入→Split分片(默认=Block大小=128MB)→Map映射(逐行处理)→Shuffle洗牌(排序+分区+合并，最关键！)→Reduce归约(默认1个)→Output输出到HDFS'},
  {id:'hd016',subj:'Hadoop',lvl:'A',item:'Split决定Map并行度：一个Split对应一个Map Task、默认Split=Block(128MB)；Reduce默认数量=1；Map输入key=LongWritable(字节偏移量) value=Text(行内容)'},
  {id:'hd017',subj:'Hadoop',lvl:'B',item:'Shuffle详解：Map端(输出→环形缓冲区100MB→80%阈值溢写→Partition分区→Sort排序→Combiner可选合并)→Reduce端(HTTP拉取→Merge合并→Sort排序→Group分组→传给reduce函数)'},
  {id:'hd018',subj:'Hadoop',lvl:'B',item:'Hadoop序列化：实现Writable接口(比Java Serializable轻量)；常用类型IntWritable/LongWritable/Text/DoubleWritable/NullWritable；WritableComparable=Writable+Comparable(可排序)'},
  {id:'hd019',subj:'Hadoop',lvl:'B',item:'MapReduce编程核心类：Mapper<KEYIN,VALUEIN,KEYOUT,VALUEOUT>重写map()、Reducer重写reduce()、Job配置(setMapperClass/setReducerClass/setInputFormat等)、Partitioner自定义分区'},
  {id:'hd020',subj:'Hadoop',lvl:'B',item:'Hadoop四大配置文件：hadoop-env.sh(JAVA_HOME)、core-site.xml(fs.defaultFS)、hdfs-site.xml(dfs.replication等)、yarn-site.xml(yarn.resourcemanager.hostname)'},
  {id:'hd021',subj:'Hadoop',lvl:'B',item:'Hadoop生态系统(判断是否属于)：属于→HDFS/YARN/MapReduce/Hive(数据仓库)/HBase(数据库)/Spark(计算)/ZooKeeper(协调)/Flume(采集)/Sqoop(传输)/Pig(脚本)；不属于→Spring/Java/MySQL'},
  {id:'hd022',subj:'Hadoop',lvl:'C',item:'启动集群命令：start-dfs.sh(启动HDFS)、start-yarn.sh(启动YARN)、hdfs namenode -format(首次格式化NameNode)；Web界面端口：NameNode 50070、YARN 8088'},
  {id:'hd023',subj:'Hadoop',lvl:'C',item:'Hadoop安装：SSH免密(ssh-keygen+ssh-copy-id)、JDK配置(JAVA_HOME)、hosts文件配置主机名映射、slaves/workers文件配置从节点列表'},

  // ==================== Scala & Spark (25条) ====================
  {id:'ss001',subj:'Scala & Spark',lvl:'A',item:'var vs val：var可重新赋值(变量)、val不可重新赋值(常量/类似final)；但val引用的Array内部元素可修改(arr(0)=99✅)，不能换引用(arr=newArr❌)'},
  {id:'ss002',subj:'Scala & Spark',lvl:'A',item:'Array(定长)vs ArrayBuffer(变长)：Array长度不可变但元素可改、ArrayBuffer可动态增删(+=追加 -=删除)；数组下标从0开始；val arr=Array(10,20,30)下标范围0~2'},
  {id:'ss003',subj:'Scala & Spark',lvl:'A',item:'元组Tuple：最多22个元素、下标从1开始(不是0！)、访问用._1 ._2 ._3、每个位置可存不同类型、创建后不可修改、不能用圆括号/方括号下标访问'},
  {id:'ss004',subj:'Scala & Spark',lvl:'A',item:'三大核心集合体系：List(有序可重复、默认不可变)、Set(无序不重复、自动去重)、Map(键值对key-value、map("key")取值) — 多选必考'},
  {id:'ss005',subj:'Scala & Spark',lvl:'B',item:'可变vs不可变集合：默认List/Set/Map是不可变集合(immutable)；可变集合需导入scala.collection.mutable包、如ArrayBuffer/ListBuffer/mutable.Set/mutable.Map'},
  {id:'ss006',subj:'Scala & Spark',lvl:'B',item:'def定义方法：def 方法名(参数:类型):返回类型={方法体}；返回值类型在参数列表后；最后一行自动返回不需写return；Unit表示无返回值(类似void)'},
  {id:'ss007',subj:'Scala & Spark',lvl:'B',item:'常用集合操作：.map(映射) .filter(过滤) .reduce(归约) .fold(折叠) .foreach(遍历) .mkString(拼接) .head/.tail(首/尾) .take(n)(取前n) .length(长度)'},
  {id:'ss008',subj:'Scala & Spark',lvl:'B',item:'模式匹配：变量 match { case 值 => 结果; case _ => 默认 }；_匹配任意值；支持类型匹配 case s:String=>、守卫条件 case x if x>0=>'},
  {id:'ss009',subj:'Scala & Spark',lvl:'C',item:'Scala基础语法：注释//和/* */、语句末尾分号可省略、类型推断(自动推断变量类型)、字符串插值s"Hello $name"、多行字符串"""..."""'},
  {id:'ss010',subj:'Scala & Spark',lvl:'A',item:'Spark核心优势 vs MapReduce：基于内存计算(中间结果存内存而非磁盘)、DAG调度优化、支持多种计算范式(批/流/SQL/ML)；不是"仅支持离线"！'},
  {id:'ss011',subj:'Scala & Spark',lvl:'A',item:'RDD全称Resilient Distributed Dataset(弹性分布式数据集)、Spark最核心数据抽象、不可变、可分区的、可并行计算、容错(血缘依赖关系Lineage)、可持久化'},
  {id:'ss012',subj:'Scala & Spark',lvl:'A',item:'RDD五大特性(必考多选)：①可分区的(Partition)②可并行计算(compute)③有容错机制(血缘依赖dependencies)④不可变(只读)⑤可持久化(可缓存)；【不能直接修改数据！不属于："自带计算函数"】'},
  {id:'ss013',subj:'Scala & Spark',lvl:'A',item:'转换(Transformation)vs行动(Action)：转换是惰性求值(不立即执行，只是记录操作)→map/filter/flatMap/groupByKey/reduceByKey；行动触发计算→count/collect/reduce/first/take/foreach/saveAsTextFile'},
  {id:'ss014',subj:'Scala & Spark',lvl:'B',item:'创建RDD三种方式：①sc.parallelize(集合)②sc.textFile("路径")从外部存储读取③从其他RDD转换。sc是SparkContext对象'},
  {id:'ss015',subj:'Scala & Spark',lvl:'B',item:'RDD依赖关系：窄依赖(父分区→1个子分区，如map/filter，无需Shuffle)vs宽依赖(父分区→多个子分区，如groupByKey/reduceByKey，触发Shuffle)'},
  {id:'ss016',subj:'Scala & Spark',lvl:'B',item:'RDD持久化/缓存：cache()=persist(MEMORY_ONLY)缓存到内存；persist()可指定级别MEMORY_ONLY/MEMORY_AND_DISK/MEMORY_ONLY_SER等；避免重复计算、提高迭代性能'},
  {id:'ss017',subj:'Scala & Spark',lvl:'B',item:'Spark四种运行模式：Local(本地开发测试)、Standalone(Spark自带集群)、YARN(Hadoop集群上运行)、Mesos(通用集群管理器)'},
  {id:'ss018',subj:'Scala & Spark',lvl:'C',item:'Spark生态组件：Spark Core(核心引擎)、Spark SQL(结构化数据)、Spark Streaming(实时流处理/微批)、MLlib(机器学习)、GraphX(图计算)'},

  // ==================== HBase / ZK / 大数据概念 (20条) ====================
  {id:'hz001',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase定位：基于HDFS的列式存储分布式NoSQL数据库，适合PB级海量数据的实时随机读写，CAP定理中强调CP(一致性+分区容错)'},
  {id:'hz002',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase架构四角色：HMaster(主节点-DDL/Region分配/负载均衡/故障恢复)、RegionServer(从节点-处理读写/管理Region)、ZooKeeper(HMaster选举/元数据存储/集群协调)、Client(直接与RegionServer交互)'},
  {id:'hz003',subj:'HBase / ZooKeeper',lvl:'A',item:'HBase数据模型层次：NameSpace命名空间→Table表→Row行(RowKey唯一标识)→Column Family列族(建表时定义)→Column Qualifier列限定符→Timestamp时间戳(版本号)→Cell单元格'},
  {id:'hz004',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase五大特点：①列式存储②稀疏性(空列不占空间)③易扩展(加RegionServer即可)④海量存储(PB级)⑤高并发读写；Apache顶级项目2010年'},
  {id:'hz005',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase vs 传统关系数据库：列式vs行式、水平扩展vs垂直、仅RowKey索引vs多列索引、无事务vs ACID、灵活Schema vs 固定Schema、适合简单海量读写 vs 复杂查询'},
  {id:'hz006',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase关键配置：hbase.cluster.distributed=true(分布式模式)、HBASE_MANAGES_ZK=false(使用外部ZK)、/etc/profile配环境变量、Master Web默认端口16010(1.0+)'},
  {id:'hz007',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase Shell命令：create建表、put插入/更新、get查单行、scan扫描、delete删除cell、disable+drop删表、list列出所有表、describe查看表结构'},
  {id:'hz008',subj:'HBase / ZooKeeper',lvl:'B',item:'RowKey设计(简答高频)：①长度适中(太长浪费空间)②散列性(避免热点Region写入)③业务含义(方便范围Scan查询)；常用优化技巧：加盐(Salting)、哈希(Hashing)、反转(Reversing)'},
  {id:'hz009',subj:'HBase / ZooKeeper',lvl:'B',item:'HBase底层存储：数据以HFile格式存储在HDFS上、MemStore内存缓存+WAL(Write Ahead Log预写日志)保证数据不丢失、Flush将内存数据刷写到HDFS'},
  {id:'hz010',subj:'HBase / ZooKeeper',lvl:'A',item:'ZooKeeper核心机制：集群2n+1台(奇数)、允许n台失效；Leader选举用过半机制(>半数同意)；ZNode最大数据量1MB；每个ZK节点有唯一myid文件存放ID'},
  {id:'hz011',subj:'HBase / ZooKeeper',lvl:'A',item:'ZNode四种类型：持久(Persistent-需手动删除)、临时(Ephemeral-客户端断开自动删除/用于故障检测)、持久顺序(Persistent Sequential)、临时顺序(Ephemeral Sequential)'},
  {id:'hz012',subj:'HBase / ZooKeeper',lvl:'A',item:'ZK典型应用场景：①统一命名服务②配置管理(集群配置集中推送)③集群管理(监控节点上下线/用临时节点)④分布式锁⑤Leader选举(HDFS HA、HBase HMaster)⑥分布式队列'},
  {id:'hz013',subj:'HBase / ZooKeeper',lvl:'B',item:'ZK客户端命令：zkCli.sh进入、ls /查看子节点、create创建、get获取数据+属性、set修改、delete删除、stat查看状态、quit退出；zkServer.sh status查看ZK节点状态(Leader/Follower)'},
  {id:'hz014',subj:'HBase / ZooKeeper',lvl:'B',item:'ZK配置文件zoo.cfg：dataDir数据目录、clientPort客户端端口(默认2181)、server.X=host:port1:port2(X与myid对应/A用于Leader选举通信/B用于数据同步)、tickTime心跳间隔'},
  {id:'hz015',subj:'HBase / ZooKeeper',lvl:'C',item:'大数据4V特点：Volume(数据量大TB→PB→ZB)、Velocity(产生和处理速度快)、Variety(数据类型多样结构化/半结构化/非结构化)、Value(价值密度低≠高！)'},
  {id:'hz016',subj:'HBase / ZooKeeper',lvl:'C',item:'大数据处理三种范式：批处理(MapReduce/Spark-高延迟分钟-小时)、流处理(Spark Streaming/Flink/Storm-低延迟毫秒-秒)、交互式查询(Hive/Spark SQL/Impala-中等延迟)'},
  {id:'hz017',subj:'HBase / ZooKeeper',lvl:'C',item:'HBase安装前提：JDK、Hadoop(HDFS+YARN)、ZooKeeper、SSH免密；启动顺序：Hadoop→ZooKeeper→HBase；用jps查看进程：HMaster/HRegionServer/QuorumPeerMain(ZK)'},

  // ==================== Web前端 新增 (25条) ====================
  {id:'wf001',subj:'Web前端',lvl:'A',item:'HTML核心结构(必考选择)：<html><head>...</head><body>...</body></html>，head放<meta>/<title>/<link>/<style>元数据，body放可见内容；<title>标签定义浏览器标签栏标题放在<head>内，<h1>是页面正文标题'},
  {id:'wf002',subj:'Web前端',lvl:'A',item:'块级vs行内元素(判断+多选高频)：<div>/<p>/<h1>~<h6>是块级(独占一行可设宽高)；<span>/<a>/<img>/<input>是行内/内联元素(不换行宽高无效)；常考判断"<div>是行内<span>是块级"→错'},
  {id:'wf003',subj:'Web前端',lvl:'A',item:'超链接<a href="url">、图片<img src="路径" alt="替代文本">；<ul>无序列表(圆点)/<ol>有序列表(数字)配<li>列表项；ol的type属性合法值：1/a/A/i/I(没有x)'},
  {id:'wf004',subj:'Web前端',lvl:'A',item:'表格标签体系：<table>表格/<tr>行/<td>单元格/<th>表头(粗体居中必须放<tr>内)；border边框粗细/cellspacing单元格间距/cellpadding单元格内边距/align对齐方式；border不定义背景'},
  {id:'wf005',subj:'Web前端',lvl:'A',item:'表单form+input体系：type取值text文本/password密码(圆点显示)/hidden隐藏域/submit提交按钮/radio单选/checkbox多选/email邮箱；获取值用document.表单名.字段名.value'},
  {id:'wf006',subj:'Web前端',lvl:'A',item:'CSS选择器优先级(必考)：!important > 行内style(1000) > #id(100) > .class(10) > 标签(1) > *(0)；#demo选id为demo的元素，.demo选class为demo的元素；类选择器优先级低于ID选择器'},
  {id:'wf007',subj:'Web前端',lvl:'A',item:'CSS盒模型四部分(简答必考)：content内容→padding内边距→border边框→margin外边距；box-sizing:content-box(默认width仅内容区，总宽=width+padding+border)；box-sizing:border-box(width含padding+border，总宽=width更直观)；margin透明不影响背景、padding影响背景'},
  {id:'wf008',subj:'Web前端',lvl:'A',item:'四大定位position(选择+判断)：static默认正常流、relative相对自身原位置(仍占空间)、absolute相对最近定位祖先/窗口(脱离文档流)、fixed固定视口(脱离文档流)；float也可实现定位；设置相对定位的值是position:relative'},
  {id:'wf009',subj:'Web前端',lvl:'A',item:'display属性必考：display:none隐藏且不占空间(回流)；visibility:hidden隐藏但占空间(只重绘)；block块级/inline行内/inline-block行内块/flex弹性/grid网格；块级水平居中margin:0 auto(须有宽度)；行内文本居中text-align:center(不能居中块级本身)'},
  {id:'wf010',subj:'Web前端',lvl:'A',item:'JS三种变量声明区别(选择+判断高频)：var函数作用域有变量提升可重复声明；let块级作用域有TDZ暂时性死区不可重复声明；const块级作用域不可重新赋值(但对象属性可修改obj.name=xx✅，obj={}❌)；推荐const优先需改再let'},
  {id:'wf011',subj:'Web前端',lvl:'A',item:'JS数据类型核心(简答+判断+选择必考)：①null vs undefined：undefined变量声明未赋值默认状态，null主动设空值；null==undefined→true，null===undefined→false；typeof null→"object"(JS历史bug)；②NaN===NaN→false(不等于自己)用isNaN()判断；③typeof undefined→"undefined"'},
  {id:'wf012',subj:'Web前端',lvl:'A',item:'DOM获取元素五大方法(选择+多选+填空必考)：getElementById(id)→单个元素/找不到返回null；getElementsByClassName/ByTagName→HTMLCollection动态集合；querySelector(CSS选择器)→单个；querySelectorAll→NodeList静态列表(可forEach)；innerHTML是属性(获取/设置内容)不是方法'},
  {id:'wf013',subj:'Web前端',lvl:'A',item:'CSS三种引入方式(简答必考)：①行内样式(元素style属性)优先级最高②内嵌样式(<head>中<style>标签)优先级中等③外部样式(<link rel="stylesheet" href=".css">)优先级最低；优先级：行内>内嵌>外部；!important可打破这个规则'},
  {id:'wf014',subj:'Web前端',lvl:'A',item:'CSS常用属性集(选择高频)：文字color颜色/font-size字号(如font-size:18px不能省略px)/font-family字体族/font-weight粗细/text-align对齐/line-height行高/text-decoration装饰；背景background-color背景色/background-image背景图；没有font-color/text-color/text-size这些属性'},
  {id:'wf015',subj:'Web前端',lvl:'A',item:'浏览器端前端三大技术(多选常考)：HTML负责结构+CSS负责样式+JavaScript负责交互；Java不是浏览器端技术不属于前端；三种注释写法：HTML<!-- -->、CSS/* */、JS //单行或/* */多行'},
  {id:'wf016',subj:'Web前端',lvl:'B',item:'CSS盒模型B卷补充考点(多选+判断)：margin不会影响元素背景区域(透明)；padding会影响元素背景区域(扩展背景色)；border默认值为0(或medium none color)；width在border-box下包含border和padding；margin可以设置负值(padding不能)；总宽度=content+padding+border+margin✔'},
  {id:'wf017',subj:'Web前端',lvl:'B',item:'表单验证流程(编程题15分必练)：form绑定onsubmit="return check()"→check函数中document.form名.字段名.value获取值→判断是否为空→为空则alert提示+return false阻止提交→验证通过则document.write输出或return true；还可用HTML5原生验证required/pattern/type="email"'},
  {id:'wf018',subj:'Web前端',lvl:'B',item:'HTML5语义化标签(选择+简答)：<header>页头/<nav>导航/<main>主体/<article>独立内容区块/<section>分节/<aside>侧栏/<footer>页脚；替代纯<div>，SEO友好+代码可读性高+可访问性好'},
  {id:'wf019',subj:'Web前端',lvl:'B',item:'CSS长度单位(选择高频)：px像素屏幕最小单位(最常用)、em相对父元素字号、rem相对根元素字号、%百分比、pt磅(1/72英寸)、cm厘米；考试常考px是像素单位'},
  {id:'wf020',subj:'Web前端',lvl:'B',item:'JS进阶考点(选择+B卷重点)：①const声明对象后obj.name="xx"✅允许(修改属性不改变引用)②parseInt("10",2)可指定进制(2~36)解析整数③Date对象new Date()获取当前时间④alert()弹出警告框⑤document.write()页面输出⑥console.log()控制台输出'},
  {id:'wf021',subj:'Web前端',lvl:'B',item:'z-index与堆叠(选择)：z-index控制定位元素在z轴上的堆叠顺序(数值越大越靠前)；只对position非static的元素有效；没有z-order/stack-level/layer这些属性；getElementById找不到返回null不是undefined'},
  {id:'wf022',subj:'Web前端',lvl:'B',item:'HTML标签杂项(选择+判断)：<img>自闭合标签alt属性用于图片无法显示时的替代文本；<input type="text" readonly>只读状态不可编辑但可选中复制(≠disabled)；HTML标签可嵌套但不能交叉嵌套(如<p><div></p></div>❌)；注释<!-- -->'},
  {id:'wf023',subj:'Web前端',lvl:'C',item:'CSS Float浮动(选择)：float:left/right元素浮动文字环绕、脱离文档流导致父容器高度塌陷；清除浮动方法clear:both或overflow:hidden或::after伪元素清除法(clearfix)；现代替代方案flexbox更推荐'},
  {id:'wf024',subj:'Web前端',lvl:'C',item:'CSS Flexbox弹性布局(补充)：display:flex开启；容器属性justify-content主轴对齐/align-items交叉轴对齐/flex-direction方向/flex-wrap换行；项目属性flex占比例；一维布局首选比float方便'},
  {id:'wf025',subj:'Web前端',lvl:'C',item:'响应式与媒体查询(补充)：@media screen and (max-width:768px){...}根据屏幕宽度应用不同CSS；viewport元标签<meta name="viewport" content="width=device-width">适配移动端；HTML特殊字符 空格 <小于 >大于 ©版权'},
];

// 学习建议顺序
const STUDY_ORDER = ['Linux', 'Java Web', 'Hadoop', 'Scala & Spark', 'HBase / ZooKeeper', 'Web前端'];
